=== sabanin/JavaEpam/Project3/bank.xsd
<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 
	<xsd:element name="Bank" type="BankType"/>
	<xsd:complexType name="BankType">
		<xsd:sequence>
		<xsd:element name="BankDeposit" type="BankDepositeType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="BankDepositeType">
		<xsd:sequence>
		<xsd:element name="Name" type="xsd:string"/>
		<xsd:element name="Country" type="xsd:string"/>
		<xsd:element name="Type">
			<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="До востребования"/>
				<xsd:enumeration value="Срочный"/>
				<xsd:enumeration value="Расчетный"/>
				<xsd:enumeration value="Накопительный"/>
				<xsd:enumeration value="Сберегательный"/>
				<xsd:enumeration value="Металлический"/>
			</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
		<xsd:element name="Depositor" type="xsd:string"/>
		<xsd:element name="AccountId" type="xsd:decimal"/>
		<xsd:element name="AmountOnDeposit">
			<xsd:simpleType>
			<xsd:restriction base="xsd:decimal">
				<xsd:minExclusive value="100"/>
			</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
		<xsd:element name="Profitability">
			<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="\d%"/>
			</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
		<xsd:element name="Date" type="xsd:date"/>
		</xsd:sequence>
		<xsd:attribute name="depositeId" type="xsd:decimal" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== sabanin/JavaEpam/Project3/bank.xml
<?xml version="1.0" encoding="windows-1251"?>
<Bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="bank.xsd">
<BankDeposit depositId="13">
	<Name>Первый Банк</Name> 
	<Country>Украина</Country>
	<Type>Накопительный</Type>
	<Depositor>Ростик Вишневский</Depositor>
	<AccountId>1516</AccountId>
	<AmountOnDeposit>7879</AmountOnDeposit>
	<Profitability>11%</Profitability>
	<Date>15-08-2003</Date>
</BankDeposit>
<BankDeposit depositId="42">
	<Name>Второй, но все равно хороший Банк</Name> 
	<Country>Украина</Country>
	<Type>Срочный</Type>
	<Depositor>Зак Браф</Depositor>
	<AccountId>6589</AccountId>
	<AmountOnDeposit>464878</AmountOnDeposit>
	<Profitability>9%</Profitability>
	<Date>29-12-2005</Date>
</BankDeposit>
<BankDeposit depositId="66">
	<Name>Хороший Банк</Name> 
	<Country>Швейцария</Country>
	<Type>Металлический</Type>
	<Depositor>Вдовиченко Оксана</Depositor>
	<AccountId>1314</AccountId>
	<AmountOnDeposit>101</AmountOnDeposit>
	<Profitability>33%</Profitability>
	<Date>10-12-2013</Date>
</BankDeposit>
</Bank>
